language: python

# command to run tests
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest
before_install: |
  openssl aes-256-cbc -K $encrypted_6578a7921867_key -iv $encrypted_6578a7921867_iv -in test.synapseConfig.enc -out test.synapseConfig -d
  mv test.synapseConfig ~/.synapseConfig
